#!/usr/bin/env python
import asyncio
import sys

from app.app import app
from cleo.io.inputs.argv_input import ArgvInput


if __name__ == "__main__":
    input_ = ArgvInput()
    input_.set_stream(sys.stdin)

    status = asyncio.run(app.handle_command(input_))
    sys.exit(status)
