"""
Create messages table

Revision ID: ddc225c7a9f4
Revises: c8d0f25df695
Create Date: 2025-04-05 15:07:28.878394
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ddc225c7a9f4"
down_revision: str | None = "c8d0f25df695"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"),
            sa.Identity(always=True),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("headers", sa.Text(), nullable=False),
        sa.Column("queue_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True).with_variant(
                mysql.DATETIME(timezone=True, fsp=6), "mysql"
            ),
            nullable=False,
        ),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True).with_variant(
                mysql.DATETIME(timezone=True, fsp=6), "mysql"
            ),
            nullable=False,
        ),
        sa.Column(
            "delivered_at",
            sa.DateTime(timezone=True).with_variant(
                mysql.DATETIME(timezone=True, fsp=6), "mysql"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_available_at"), "messages", ["available_at"], unique=False
    )
    op.create_index(
        op.f("ix_messages_delivered_at"), "messages", ["delivered_at"], unique=False
    )
    op.create_index(
        op.f("ix_messages_queue_name"), "messages", ["queue_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_queue_name"), table_name="messages")
    op.drop_index(op.f("ix_messages_delivered_at"), table_name="messages")
    op.drop_index(op.f("ix_messages_available_at"), table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
