"""
Create cache table and cache_locks table

Revision ID: 2467f0e64118
Revises: ddc225c7a9f4
Create Date: 2025-04-05 15:07:29.878394
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "2467f0e64118"
down_revision: str | None = "ddc225c7a9f4"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column(
            "expiration",
            sa.Integer().with_variant(mysql.INTEGER(unsigned=True), "mysql"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_cache_expiration"), "cache", ["expiration"], unique=False)
    op.create_table(
        "cache_locks",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column(
            "expiration",
            sa.Integer().with_variant(mysql.INTEGER(unsigned=True), "mysql"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        op.f("ix_cache_locks_expiration"), "cache_locks", ["expiration"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cache_locks_expiration"), table_name="cache_locks")
    op.drop_table("cache_locks")
    op.drop_index(op.f("ix_cache_expiration"), table_name="cache")
    op.drop_table("cache")
    # ### end Alembic commands ###
